defmodule ThreadlinePhoenixWeb.Auth.SudoHTML do
  @moduledoc """
  HTML templates for sudo/re-authentication mode.

  Single-purpose page: password field + confirm button, centered in a
  narrow column matching the login form width. Follows GitHub's sudo
  pattern per D-20 to D-23.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use ThreadlinePhoenixWeb, :html

  def new(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        Confirm your password
        <:subtitle>For your security, please re-enter your password to continue.</:subtitle>
      </.header>

      <.form :let={f} for={@form} action={~p"/users/sudo"} method="post" class="space-y-4">
        <input type="hidden" name="sudo[return_to]" value={@return_to} />
        <.input
          field={f[:password]}
          type="password"
          label="Password"
          autocomplete="current-password"
          autofocus
          required
        />
        <.button class="w-full">Confirm password</.button>
      </.form>

      <p class="mt-4 text-center text-sm">
        <.link navigate={@return_to || ~p"/"} class="text-brand hover:underline">
          Go back
        </.link>
      </p>
    </div>
    """
  end
end
