defmodule ThreadlinePhoenixWeb.Auth.SudoController do
  @moduledoc """
  Controller for sudo/re-authentication mode.

  When a user accesses a sensitive operation protected by `Sigra.Plug.RequireSudo`,
  they are redirected here to re-enter their password. On success, the session's
  `sudo_at` timestamp is updated and the user is redirected back.

  Follows GitHub's sudo pattern: redirect to `/users/sudo` with `return_to` param,
  user enters password, gets redirected back. Form submits via HTTP POST (not
  LiveView event) per D-21.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use ThreadlinePhoenixWeb, :controller

  def new(conn, _params) do
    form = Phoenix.Component.to_form(%{"password" => ""}, as: "sudo")
    render(conn, :new, return_to: conn.params["return_to"] || ~p"/", form: form)
  end

  def create(conn, %{"sudo" => %{"password" => password, "return_to" => return_to}}) do
    user = conn.assigns.current_scope.user

    case Sigra.Crypto.verify_password(password, user.hashed_password) do
      true ->
        session = conn.private[:sigra_session]
        ThreadlinePhoenix.Accounts.confirm_sudo(session.hashed_token)

        # Validate return_to is a local path (not an external URL)
        safe_return_to =
          if return_to && String.starts_with?(return_to, "/") && !String.starts_with?(return_to, "//") do
            return_to
          else
            ~p"/"
          end

        conn
        |> put_flash(:info, "Password confirmed.")
        |> redirect(to: safe_return_to)

      false ->
        conn
        |> put_flash(:error, "Incorrect password. Please try again.")
        |> render(:new, return_to: return_to)
    end
  end

  def create(conn, %{"sudo" => %{"password" => password}}) do
    create(conn, %{"sudo" => %{"password" => password, "return_to" => ~p"/"}})
  end
end
