import Config

# Sigra Cloak vault — dev-only key (generate a unique CLOAK_KEY for production)
System.put_env(
  "CLOAK_KEY",
  Base.encode64(:crypto.hash(:sha256, "threadline_phoenix_dev_cloak_v1"))
)

# Configure your database
config :threadline_phoenix, ThreadlinePhoenix.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("DB_HOST", "localhost"),
  port: System.get_env("DB_PORT", "5432") |> String.to_integer(),
  database: "threadline_phoenix_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :threadline_phoenix, ThreadlinePhoenixWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "DbzN8zJ6SETpFXu93UHcyjKgypLGT5Ibe0507ctc7EyjHlf9DrkZvT0OR9HECBOq",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :threadline_phoenix, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Demo drift: the redaction policy masks both `internal_note_body` and `body`,
# but the deployed trigger (priv/repo/migrations) only masks `internal_note_body`
# — i.e. the policy was updated and the triggers haven't been regenerated yet.
# This makes the operator surface's redaction-drift screen demonstrate a real
# finding instead of the always-green state. Capture is unaffected (the deployed
# trigger still redacts internal_note_body), so row-history [REDACTED] holds.
config :threadline, :trigger_capture,
  tables: %{
    "ticket_replies" => [
      mask: ["internal_note_body", "body"],
      store_changed_from: true
    ]
  }

# `audit_events` exists (see migrations) but has no capture trigger, so listing
# it as expected makes the coverage screen demonstrate a real "Needs capture"
# row + a non-zero header badge instead of the always-green state. The
# trigger-coverage evidence subject reports the same uncovered_count, so the
# evidence and coverage stories agree.
config :threadline, :verify_coverage,
  expected_tables: [
    "posts",
    "organizations",
    "org_memberships",
    "agents",
    "tickets",
    "ticket_replies",
    "audit_events"
  ]

# Sigra email delivery (dev) — adapter is set on the raw Swoosh.Mailer
# module, not the Sigra.Mailer behaviour wrapper.
config :threadline_phoenix, ThreadlinePhoenix.Mailer, adapter: Swoosh.Adapters.Local

config :swoosh, :api_client, false

config :threadline_phoenix, ThreadlinePhoenixWeb.OperatorUser,
  admin_emails: ["admin@example.com"],
  admin_user_ids: []

config :threadline_phoenix,
  demo_epoch: ~U[2026-05-27 12:00:00Z],
  demo_seed_password: "password123456"

# Demo seed tail enables retention at runtime (`Demo.Seed.RetentionTail`) before
# `Threadline.Retention.purge/1`. Keep `:enabled` false here so the background
# pruner does not start before `ThreadlinePhoenix.Repo`.
config :threadline,
  retention: [enabled: false, keep_days: 30, delete_empty_transactions: true]
