defmodule Mix.Tasks.Threadline.Gen.Triggers do
  @shortdoc "Generates an Ecto migration that installs audit triggers on tables"

  @moduledoc """
  Generates an Ecto migration that installs Threadline audit triggers on the
  specified tables.

  ## Usage

      mix threadline.gen.triggers --tables users
      mix threadline.gen.triggers --tables users,posts,comments

  Each invocation writes one migration whose statements create or replace the
  audit trigger on each listed table (`CREATE OR REPLACE TRIGGER`, PostgreSQL 14
  or later). Run `mix ecto.migrate` to apply.

  The trigger calls `threadline_capture_changes()`, which must already be
  installed via `mix threadline.install`.

  With before-values capture for opted-in tables:

      mix threadline.gen.triggers --tables posts --store-changed-from
      mix threadline.gen.triggers --tables posts --store-changed-from --except-columns secret_token,internal_score

  That gives each listed table its own capture function and wires its trigger
  to it. The function name is derived from the table's schema and name: a table
  in the `public` schema whose name is at most 36 bytes gets
  `threadline_capture_changes_` followed by the table name, and any other table
  gets a shortened name ending in a hash of its schema and table, so no two
  tables share a function. Migrations generated without `--store-changed-from`
  keep the default global `threadline_capture_changes()` trigger body
  **unless** the table has `:exclude` / `:mask` rules under
  `config :threadline, :trigger_capture` (see README).

  ## Primary keys

  When the generated migration runs, it reads the table's real primary key
  from the database and passes its columns to the capture function as
  trigger arguments, so audit rows record the real key rather than always
  assuming a column named `id`. This covers a single primary-key column of
  any supported name, and a composite primary key of more than one column.
  A primary key with `INCLUDE` columns only passes its actual key columns;
  `INCLUDE` columns are never part of the trigger arguments.

  Supported primary-key column types: `smallint`, `integer`, `bigint`,
  `text`, `varchar`, `char`, `citext`, `uuid`, `date`, `timestamp` (without
  time zone), enum types, and domains over any of these. A column outside
  this list, such as `timestamptz`, `numeric`, a float, `json`/`jsonb`, an
  array, or `bytea`, has no stable text form for an audit key and stops the
  migration, naming the column and its type.

  A table with **no primary key** needs a `primary_key:` entry in
  `config/config.exs` naming a unique index over `NOT NULL` columns. For a
  Phoenix `many_to_many` join table such as `posts_tags`, with a unique
  index over `(post_id, tag_id)`:

      config :threadline, :trigger_capture,
        tables: %{"posts_tags" => [primary_key: ["post_id", "tag_id"]]}

  Then regenerate:

      mix threadline.gen.triggers --tables posts_tags

  A table that already has a primary key must not also declare
  `primary_key:` — Threadline discovers it automatically, and the migration
  stops with a hint to remove the redundant entry. A primary-key or declared
  `primary_key:` column that also appears in the table's `:mask` or
  `:exclude` stops the migration too: redacting a key column would erase row
  identity from the audit trail.

  A trigger generated by a release before this primary-key resolution keeps
  capturing exactly as it did until you regenerate it; regenerating upgrades
  it to a trigger that resolves the real key. When a write's primary key
  cannot be resolved — such as before regenerating, or when every key
  column would come back `NULL` — the row's `table_pk` is recorded as an
  empty `{}` rather than failing the write.

  ## Redaction (`config :threadline, :trigger_capture`)

  At task start the host app config is loaded (`Mix.Task.run("app.config", [])`).
  Per-table entries under `:tables` may set `:exclude`, `:mask`, optional
  `:mask_placeholder`, `:store_changed_from`, `:except_columns`, and
  `:primary_key` (see "Primary keys" above). Overlap between `:exclude` and
  `:mask` is validated before writing the migration. A key names a table the
  way `--tables` does, so `posts` and `public.posts` are the same table; one
  table under two keys stops the task.

  ## Rerunning

  Run the task again for tables that already have a trigger migration, for
  example after changing `:trigger_capture` redaction rules or to clear a
  `Drift detected` status. It writes a new migration. When the table-derived
  name is already taken, the migration gets a numbered name, such as
  `threadline_triggers_posts_2`, and a matching numbered module. A rerun for a
  different table set, such as `posts` after `posts,users`, keeps the
  un-numbered `threadline_triggers_posts`. The new migration replaces the
  trigger in place, so capture has no gap.

  A capture function the migration no longer needs, such as the per-table
  function of a table that returns to the default trigger, is dropped only
  after every trigger in the migration is re-pointed, and only when no trigger
  still uses it. If a trigger on some table still uses it, the function is kept
  and `mix ecto.migrate` prints a WARNING naming those tables. The drop never
  cascades, and a function that does not exist is skipped.

  Rolling back a rerun migration keeps capture on for the tables it re-pointed.
  Rolling back does not restore the earlier capture policy: the trigger keeps the
  policy the rerun installed. If the rerun had removed redaction rules, a rolled
  back rerun leaves capture running unredacted until you regenerate, and
  `mix threadline.policy.show` flags the mismatch once your config lists those
  rules again. The generated `down` says the
  same in a comment. To stop capturing a table, write a migration that drops its
  trigger.

  ## Tables that shared a capture function

  Releases up to 0.10.2 could give two tables one capture function. For
  example, `public.billing_invoices` and `billing.invoices` both used
  `threadline_capture_changes_billing_invoices`, so one table could apply the
  other's redaction rules. Later releases give `billing.invoices` a hashed name
  of its own, and `public.billing_invoices` keeps the old one.

  Two orders are safe: regenerate both tables in one command, or regenerate the
  table outside `public` (or the table with the long name) first:

      mix threadline.gen.triggers --tables billing_invoices,billing.invoices

  If you regenerate only the table that keeps the old name, `mix ecto.migrate`
  stops with an error naming the other tables whose triggers still use that
  function. Its hint gives the command to run instead, such as
  `mix threadline.gen.triggers --tables billing_invoices,billing.invoices`.
  Nothing from that migration is applied, so capture keeps running as before.
  Delete the refused migration file, then generate the suggested one.

  A WARNING from `mix ecto.migrate` that keeps a capture function because
  triggers on some tables still use it means those tables should be
  regenerated too. The WARNING also appears when a table in the `public` schema
  legitimately owns that function name, for example after regenerating
  `billing.invoices` on its own. Regenerating the tables it names is always
  safe.

  ## Options

  * `--tables` — comma-separated list of table names (required). Each table
    is listed once: `posts,public.posts` names one table twice and stops the
    task.
  * `--store-changed-from` — emit per-table capture functions that persist sparse
    `changed_from` JSON on UPDATE (default: off)
  * `--except-columns` — comma-separated column names excluded from both
    `changed_fields` and `changed_from` when `--store-changed-from` is set
    (alphanumeric and underscore only). Merged with `:except_columns` from config.
  * `--dry-run` — print `table=… exclude=… mask=…` per table and skip writing a migration
  * `--migrations-path` — directory the migration is written to, used as given
    relative to the current directory. The repo is not loaded.
  * `--repo` / `-r` — one repo; the migration goes to that repo's migrations
    directory, the same place `mix threadline.install` writes.

  Without `--migrations-path` or `--repo`, the task uses the first repo in
  `:ecto_repos` and its `:priv` setting. A configured repo that cannot be
  loaded falls back to `priv/repo/migrations`, with a warning naming it. In an
  umbrella, run the task from the child app's directory.

  ## Long table names

  In default capture mode, a table whose trigger name would exceed 63 bytes gets
  the name PostgreSQL would store, `threadline_audit_<table>` cut to 63 bytes.
  Per-table mode (redaction rules or `--store-changed-from`) works for long
  tables and for tables outside the `public` schema: their capture functions get
  hashed names that fit in 63 bytes. A `--tables` value that is not a valid
  identifier, or is longer than 63 bytes, stops the task with an error that
  names the host table and its size in bytes.

  ## Guards

  The task exits non-zero if `audit_transactions` or `audit_changes` is in the
  table list. Installing audit triggers on Threadline's own tables would cause
  recursive loops in the audit tables themselves.
  """

  use Mix.Task
  import Mix.Generator

  alias Threadline.Capture.{Naming, RedactionPolicy, TriggerCaptureConfig, TriggerSQL}
  alias Threadline.Mix.{MigrationsPath, MigrationVersion, TriggerMigration}
  alias Threadline.StorageSchema

  @column_name ~r/^[A-Za-z0-9_]+$/

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.config", [])

    opts = parse_opts!(args)

    tables =
      opts
      |> Keyword.get(:tables, "")
      |> String.split(",", trim: true)
      |> Enum.map(&String.trim/1)

    if tables == [] do
      Mix.raise("--tables is required. Example: mix threadline.gen.triggers --tables users,posts")
    end

    pairs = parse_tables!(tables)
    forbidden = Enum.filter(tables, &StorageSchema.threadline_table?/1)

    if forbidden != [] do
      Mix.raise(
        "Cannot install audit triggers on Threadline's own tables: #{Enum.join(forbidden, ", ")}. " <>
          "This would cause a recursive audit loop."
      )
    end

    reject_duplicate_tables!(tables, pairs)

    cli_store_changed_from = Keyword.get(opts, :store_changed_from, false)

    cli_except_columns =
      opts
      |> Keyword.get(:except_columns, "")
      |> parse_except_columns()

    capture_tables = capture_tables_by_pair!(load_capture_tables!())
    dry_run? = Keyword.get(opts, :dry_run, false)

    table_specs =
      Enum.zip_with(tables, pairs, fn table, pair ->
        {table,
         build_table_capture_spec(
           pair,
           cli_store_changed_from,
           cli_except_columns,
           capture_tables
         )}
      end)

    # Resolved before the dry-run branch, so a dry run reports the same
    # --repo errors a real run would.
    path = MigrationsPath.resolve(opts)

    if dry_run? do
      Enum.each(table_specs, fn {table, spec} ->
        o = spec.opts
        exclude = Keyword.get(o, :exclude, [])
        mask = Keyword.get(o, :mask, [])
        Mix.shell().info("table=#{table} exclude=#{inspect(exclude)} mask=#{inspect(mask)}")
      end)

      Mix.shell().info("[dry-run] no migration file written")
    else
      write_migration!(path, Enum.zip(tables, pairs), table_specs)
    end
  end

  defp parse_opts!(args) do
    {opts, _rest, invalid} =
      OptionParser.parse(args,
        strict: [
          tables: :string,
          store_changed_from: :boolean,
          except_columns: :string,
          dry_run: :boolean,
          migrations_path: :string,
          repo: :keep
        ],
        aliases: [r: :repo]
      )

    if invalid != [] do
      Mix.raise("Unknown options: #{inspect(invalid)}")
    end

    opts
  end

  # Only the user's --tables input becomes a Mix error. Derived names, such as
  # capture function names, are built to fit in 63 bytes; a derived name that
  # did not would be a bug and stays an ArgumentError.
  defp parse_tables!(tables) do
    Enum.map(tables, &StorageSchema.parse_table_identifier/1)
  rescue
    e in ArgumentError -> Mix.raise("--tables: " <> Exception.message(e))
  end

  # Two --tables entries for one table, such as posts and public.posts, would
  # emit two triggers for it, and the last one would decide its redaction.
  defp reject_duplicate_tables!(tables, pairs) do
    duplicates =
      tables
      |> Enum.zip(pairs)
      |> Enum.group_by(fn {_table, pair} -> Naming.qualified(pair) end, &elem(&1, 0))
      |> Enum.filter(fn {_qualified, names} -> length(names) > 1 end)
      |> Enum.sort()

    if duplicates != [] do
      listed =
        Enum.map_join(duplicates, "; ", fn {qualified, names} ->
          "#{Enum.join(names, ", ")} (all #{qualified})"
        end)

      Mix.raise("--tables lists the same table more than once: #{listed}. List each table once.")
    end
  end

  # Redaction config keyed by schema.table, so a config key and a --tables
  # value that spell one table differently, such as posts and public.posts,
  # still find each other.
  defp capture_tables_by_pair!(capture_tables) do
    grouped = Enum.group_by(capture_tables, fn {key, _entry} -> config_key_qualified!(key) end)

    conflicts =
      for {qualified, [_, _ | _] = entries} <- grouped do
        "#{entries |> Enum.map(&elem(&1, 0)) |> Enum.sort() |> Enum.join(", ")} (all #{qualified})"
      end

    if conflicts != [] do
      Mix.raise(
        "config :threadline, :trigger_capture lists the same table under more than one key: " <>
          Enum.join(Enum.sort(conflicts), "; ") <> ". Keep one entry per table."
      )
    end

    Map.new(grouped, fn {qualified, [{_key, entry}]} -> {qualified, entry} end)
  end

  # A malformed :primary_key, :mask, :exclude, or other table entry raises
  # ArgumentError from TriggerCaptureConfig.load/0; wrapped here into a Mix
  # error so it stops the task the same way an invalid --tables value does,
  # before any migration file is written.
  defp load_capture_tables! do
    TriggerCaptureConfig.load()
  rescue
    e in ArgumentError ->
      Mix.raise("config :threadline, :trigger_capture " <> Exception.message(e))
  end

  defp config_key_qualified!(key) do
    key |> StorageSchema.parse_table_identifier() |> Naming.qualified()
  rescue
    e in ArgumentError ->
      Mix.raise("config :threadline, :trigger_capture tables: " <> Exception.message(e))
  end

  defp write_migration!(path, tables_and_pairs, table_specs) do
    File.mkdir_p!(path)

    # Versioned after every migration already in the directory, so running
    # this right after `mix threadline.install` cannot repeat a version when
    # both write here.
    [version] = MigrationVersion.next(path, 1)
    scan = TriggerMigration.scan(path)

    {name, module} =
      tables_and_pairs |> Enum.map(&elem(&1, 1)) |> TriggerMigration.resolve_name(scan)

    file = Path.join(path, "#{version}_#{name}.exs")

    # Read before the new file is written, so only earlier migrations count.
    rerun_tables =
      for {table, pair} <- tables_and_pairs,
          TriggerMigration.rerun?(pair, scan.sources),
          do: table

    create_file(file, migration_content(table_specs, module, rerun_tables))

    if rerun_tables != [] do
      Mix.shell().info(
        "These tables already have a Threadline trigger migration: " <>
          Enum.join(rerun_tables, ", ") <>
          ". Rolling back the new migration keeps their capture on."
      )
    end

    warn_shared_legacy_names(Enum.map(tables_and_pairs, &elem(&1, 1)), scan)

    Mix.shell().info("Run `mix ecto.migrate` to install the triggers.")
  end

  # Releases up to 0.10.2 gave some tables one capture function name, such as
  # public.billing_invoices and billing.invoices. Regenerating only one of
  # them can stop `mix ecto.migrate` or leave the other on the old function,
  # so the task names the other table before anything is migrated. Advice
  # only: the migration is already written, and the migrate-time guard is
  # what enforces it.
  defp warn_shared_legacy_names(pairs, scan) do
    generated = Enum.map(pairs, &Naming.pair/1)

    covered =
      scan.sources
      |> TriggerMigration.covered_pairs()
      |> Enum.reject(&(&1 in generated))

    for p <- generated,
        q <- covered,
        Naming.legacy_function_name(q) == Naming.legacy_function_name(p),
        uniq: true do
      {p, q}
    end
    |> Enum.each(fn {p, q} ->
      Mix.shell().error(
        "An earlier migration covers #{Naming.qualified(q)}, which older releases gave " <>
          "the same capture function name as #{Naming.qualified(p)}. Regenerate both " <>
          "in one command: mix threadline.gen.triggers --tables " <>
          "#{Naming.table_token(p)},#{Naming.table_token(q)}"
      )
    end)
  end

  defp build_table_capture_spec(pair, cli_store_changed_from, cli_except_columns, capture_tables) do
    entry = Map.get(capture_tables, Naming.qualified(pair), [])

    exclude = Keyword.get(entry, :exclude, [])
    mask = Keyword.get(entry, :mask, [])
    cfg_store_changed_from = Keyword.get(entry, :store_changed_from, false)
    cfg_except = Keyword.get(entry, :except_columns, [])
    primary_key = Keyword.get(entry, :primary_key)

    merged_except = (cli_except_columns ++ cfg_except) |> Enum.uniq()
    store_changed_from = cli_store_changed_from or cfg_store_changed_from

    opts =
      [
        store_changed_from: store_changed_from,
        except_columns: merged_except,
        exclude: exclude,
        mask: mask
      ]
      |> maybe_put_mask_placeholder(Keyword.get(entry, :mask_placeholder))
      |> maybe_put_primary_key(primary_key)

    if exclude != [] or mask != [] do
      RedactionPolicy.validate!(opts)
    end

    needs_per_table = store_changed_from or exclude != [] or mask != []

    %{needs_per_table: needs_per_table, opts: opts}
  end

  defp maybe_put_mask_placeholder(kw, nil), do: kw

  defp maybe_put_mask_placeholder(kw, placeholder) when is_binary(placeholder) do
    Keyword.put(kw, :mask_placeholder, placeholder)
  end

  defp maybe_put_primary_key(kw, nil), do: kw
  defp maybe_put_primary_key(kw, primary_key), do: Keyword.put(kw, :primary_key, primary_key)

  defp parse_except_columns(""), do: []

  defp parse_except_columns(raw) do
    raw
    |> String.split(",", trim: true)
    |> Enum.map(&String.trim/1)
    |> Enum.reject(&(&1 == ""))
    |> Enum.map(fn col ->
      if Regex.match?(@column_name, col) do
        col
      else
        Mix.raise(
          "--except-columns must list alphanumeric/underscore column names only; invalid: #{inspect(col)}"
        )
      end
    end)
  end

  defp migration_content(table_specs, module, rerun_tables) do
    # Every trigger is re-pointed before any guard runs or any old function
    # is retired, so both see the final state of every table in this
    # migration. A guard that raises rolls the whole migration back.
    up_body =
      [
        function_ups(table_specs),
        trigger_ups(table_specs),
        guard_ups(table_specs),
        retire_ups(table_specs)
      ]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n\n")

    """
    defmodule #{module} do
      use Ecto.Migration

      def up do
    #{up_body}
      end

      def down do
    #{down_body(table_specs, rerun_tables)}
      end
    end
    """
  end

  # A default-mode trigger with arguments must never run against an older
  # global body, and un-regenerated no-arg triggers must move to the new
  # body's legacy branch — so the global function is refreshed first,
  # whenever this migration includes at least one default-mode table.
  defp function_ups(table_specs) do
    global_line =
      if Enum.any?(table_specs, fn {_t, %{needs_per_table: n?}} -> not n? end) do
        [execute_line(TriggerSQL.install_function())]
      else
        []
      end

    per_table_lines =
      table_specs
      |> Enum.filter(fn {_t, %{needs_per_table: n?}} -> n? end)
      |> Enum.map(fn {t, %{opts: opts}} ->
        execute_line(TriggerSQL.install_function_for_table(t, opts))
      end)

    Enum.join(global_line ++ per_table_lines, "\n\n")
  end

  defp trigger_ups(table_specs) do
    Enum.map_join(table_specs, "\n\n", fn
      {t, %{needs_per_table: true, opts: opts}} ->
        execute_line(TriggerSQL.create_trigger(t, :per_table, trigger_block_opts(opts)))

      {t, %{needs_per_table: false, opts: opts}} ->
        execute_line(TriggerSQL.create_trigger(t, :default, trigger_block_opts(opts)))
    end)
  end

  # Options PrimaryKeySQL.create_trigger_block/3 reads, carried through from
  # the table's own config entry (see build_table_capture_spec/4).
  defp trigger_block_opts(opts) do
    [redacted_columns: redacted_columns(opts)]
    |> maybe_put_primary_key(Keyword.get(opts, :primary_key))
  end

  # The same exclude ++ mask list the table's per-table function redacts, so
  # a detected primary-key column can never disagree with what the function
  # itself strips or masks.
  defp redacted_columns(opts) do
    (Keyword.get(opts, :exclude, []) ++ Keyword.get(opts, :mask, [])) |> Enum.uniq()
  end

  # A per-table function this migration rewrote must have no trigger user
  # other than its own table; see TriggerSQL.function_owner_guard/2.
  defp guard_ups(table_specs) do
    table_specs
    |> Enum.filter(fn {_t, %{needs_per_table: n?}} -> n? end)
    |> Enum.map_join("\n\n", fn {t, _spec} ->
      execute_line(TriggerSQL.function_owner_guard(t))
    end)
  end

  # The functions a table may have used before this migration: its 0.10.x
  # name, and its own per-table function when it now uses the global one. A
  # function that any trigger in this migration now calls is never a
  # candidate. Each drop happens only if no trigger still uses the function;
  # otherwise the migration keeps it and prints a WARNING.
  defp retire_ups(table_specs) do
    table_specs
    |> retire_set()
    |> Enum.map_join("\n\n", &execute_line(TriggerSQL.drop_function_if_unused(&1)))
  end

  defp retire_set(table_specs) do
    in_use =
      for {t, %{needs_per_table: true}} <- table_specs,
          into: MapSet.new(),
          do: Naming.function_name(t)

    table_specs
    |> Enum.flat_map(&retire_candidates/1)
    |> Enum.uniq()
    |> Enum.reject(&MapSet.member?(in_use, &1))
  end

  defp retire_candidates({t, %{needs_per_table: true}}), do: [Naming.legacy_function_name(t)]

  defp retire_candidates({t, _spec}),
    do: Enum.uniq([Naming.legacy_function_name(t), Naming.function_name(t)])

  # The function a table's trigger calls once this migration is applied.
  defp current_function({t, %{needs_per_table: true}}), do: Naming.function_name(t)
  defp current_function({_t, _spec}), do: "threadline_capture_changes"

  # Rolling back only undoes what this migration was first to install. A
  # table that already had a trigger migration keeps its trigger, because
  # the earlier migration is still applied and still expects capture on.
  defp down_body(table_specs, rerun_tables) do
    first_run_specs = Enum.reject(table_specs, fn {t, _} -> t in rerun_tables end)

    trigger_downs =
      Enum.map_join(first_run_specs, "\n\n", fn {t, _} ->
        execute_line(TriggerSQL.drop_trigger(t))
      end)

    function_downs =
      first_run_specs
      |> Enum.filter(fn {_t, %{needs_per_table: n?}} -> n? end)
      |> Enum.map_join("\n\n", fn {t, _} ->
        execute_line(TriggerSQL.drop_function_if_unused(Naming.function_name(t)))
      end)

    [rerun_rollback_comment(table_specs, rerun_tables), trigger_downs, function_downs]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
  end

  # The whole SQL as an Elixir string literal. Plain inspect/1 cuts a string
  # longer than 4096 bytes and appends `<> ...`, which would corrupt the
  # migration; a table with many redacted columns passes that length.
  defp execute_line(sql),
    do: "    execute #{inspect(sql, printable_limit: :infinity, limit: :infinity)}"

  defp rerun_rollback_comment(_table_specs, []), do: ""

  defp rerun_rollback_comment(table_specs, rerun_tables) do
    ([
       "This migration replaced the audit trigger of #{Enum.join(rerun_tables, ", ")} in place.",
       "Rolling it back does not restore the earlier capture policy.",
       "Capture stays on with the policy this migration installed. To stop",
       "capturing a table, write a migration that drops its trigger, or roll back",
       "the migration that first installed it.",
       "If this migration removed redaction rules, rolling it back leaves capture",
       "running with them removed, so capture continues unredacted until you",
       "regenerate the trigger migration. `mix threadline.policy.show` and the",
       "redaction drift view flag that mismatch."
     ] ++ retired_lines(table_specs, rerun_tables))
    |> Enum.map_join("\n", &("    # " <> &1))
  end

  # For each rerun table, the capture functions this migration dropped for it
  # (each only if no trigger still used it) and the function its trigger
  # keeps using after a rollback.
  defp retired_lines(table_specs, rerun_tables) do
    retired = MapSet.new(retire_set(table_specs))

    for {t, _spec} = entry <- table_specs,
        t in rerun_tables,
        names = Enum.filter(retire_candidates(entry), &MapSet.member?(retired, &1)),
        names != [],
        line <- [
          "This migration retired #{Enum.join(names, " and ")} for #{t},",
          "unless another trigger still used it. Rolling it back does not recreate",
          "#{Enum.join(names, " or ")}; the trigger of #{t} keeps using",
          "#{current_function(entry)}."
        ],
        do: line
  end
end
