defmodule ThreadlinePhoenix.Accounts.AuditEvent do
  @moduledoc """
  Ecto schema for audit log events.

  Captures security-relevant authentication and application events with
  structured metadata. Rows are append-only (no `updated_at`): the only
  delete path is explicit retention cleanup via `Sigra.Audit.cleanup/1`
  or the optional `Sigra.Workers.AuditCleanup` Oban worker.

  Validation (action format, reserved prefixes, metadata size cap,
  forbidden keys) is delegated to `Sigra.Audit.Changeset.changeset/3`
  so that host-app customization does not weaken Sigra's audit
  guarantees.

  Generated by `mix sigra.install`. You may customize this module, but
  keep the changeset delegation to preserve audit integrity.
  """

  use Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "audit_events" do
    field :occurred_at, :utc_datetime_usec
    field :action, :string
    field :outcome, :string, default: "success"
    field :actor_id, :binary_id
    field :actor_type, :string, default: "user"
    field :target_id, :binary_id
    field :target_type, :string
    field :organization_id, :binary_id
    field :effective_user_id, :binary_id
    field :ip_address, :string
    field :user_agent, :string
    field :metadata, :map, default: %{}

    timestamps(type: :utc_datetime_usec, updated_at: false)
  end

  @doc """
  Builds a changeset for an audit event.

  Delegates validation to `Sigra.Audit.Changeset.changeset/3` which
  enforces the action regex (D-19), reserved action prefixes
  (D-17/D-18), metadata size cap (D-20), and forbidden metadata keys
  (D-23).
  """
  def changeset(event, attrs, opts \\ []) do
    Sigra.Audit.Changeset.changeset(event, attrs, opts)
  end
end
