defmodule ThreadlinePhoenix.Accounts.Emails do
  @moduledoc """
  Email builders for authentication flows.

  Each function returns a `Swoosh.Email` struct with HTML and plain text
  bodies. The HTML uses inline CSS for email client compatibility.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  import Swoosh.Email
  use Gettext, backend: ThreadlinePhoenixWeb.Gettext

  @from_address {"ThreadlinePhoenix", "noreply@example.com"}

  @font_family ~s(-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif)

  # -- Public API --

  @doc "Builds a confirmation email with link and 6-digit code."
  def confirmation_email(user, url, code) do
    code_display = code |> String.graphemes() |> Enum.join(" ")

    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, please confirm your email address by clicking the button below or entering the code.")}
    </p>
    <div style="margin: 24px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px; text-align: center;">
      <p style="margin: 0 0 4px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
        #{dgettext("sigra", "Your confirmation code:")}
      </p>
      <p style="margin: 0; font-size: 32px; font-weight: 700; line-height: 1.0; font-family: monospace; color: #18181b; letter-spacing: 0.25em;">
        #{code_display}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "This code expires in 48 hours.")}
    </p>
    #{cta_button(dgettext("sigra", "Confirm email address"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or confirm via this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "Please confirm your email address.")}

    #{dgettext("sigra", "Your confirmation code:")} #{code}

    #{dgettext("sigra", "Or confirm via this link:")} #{url}

    #{dgettext("sigra", "This link expires in 48 hours.")}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Confirm your email"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a password reset email."
  def reset_password_email(user, url) do
    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, we received a request to reset your password. If you didn't make this request, you can ignore this email.")}
    </p>
    #{cta_button(dgettext("sigra", "Reset password"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or use this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "We received a request to reset your password. If you didn't make this request, you can ignore this email.")}

    #{dgettext("sigra", "Reset your password:")} #{url}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Reset your password"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a magic link login email."
  def magic_link_email(user, url) do
    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, click the button below to log in to your account. This link expires in 10 minutes.")}
    </p>
    #{cta_button(dgettext("sigra", "Log in to %{app_name}", app_name: "ThreadlinePhoenix"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or use this link:")} #{url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "Click the link below to log in to your account. This link expires in 10 minutes.")}

    #{dgettext("sigra", "Log in:")} #{url}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Log in to %{app_name}", app_name: "ThreadlinePhoenix"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds an OAuth-only password reset guidance email."
  def oauth_reset_email(user, provider) do
    provider_name = provider |> to_string() |> String.capitalize()

    html_content = """
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Hi, it looks like you signed up using %{provider}. You can log in with %{provider} instead, or set a password from your account settings.", provider: provider_name)}
    </p>
    #{cta_button(dgettext("sigra", "Log in with %{provider}", provider: provider_name), "/users/log_in")}
    """

    text_body = """
    #{dgettext("sigra", "Hi,")}

    #{dgettext("sigra", "It looks like you signed up using %{provider}. You can log in with %{provider} instead, or set a password from your account settings.", provider: provider_name)}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Reset your password"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a suspicious login notification email."
  def suspicious_login_email(user, details) do
    ip = details |> Map.get(:ip, "Unknown") |> html_escape_string()
    geo_city = Map.get(details, :geo_city)
    geo_country = Map.get(details, :geo_country_code)

    location =
      if geo_city do
        "#{html_escape_string(geo_city)}, #{html_escape_string(geo_country)}"
      else
        "Unknown"
      end

    device = details |> Map.get(:device, "Unknown device") |> html_escape_string()

    time =
      Map.get(details, :time, DateTime.utc_now())
      |> Calendar.strftime("%Y-%m-%d %H:%M:%S UTC")

    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "New Sign-In Detected")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "We noticed a new sign-in to your account from an unrecognized device or location.")}
    </p>
    <div style="margin: 16px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px;">
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "IP address:")}</strong> #{ip}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Location:")}</strong> #{location}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Device:")}</strong> #{device}
      </p>
      <p style="margin: 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Time:")}</strong> #{time}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, you can safely ignore this email.")}
    </p>
    #{cta_button(dgettext("sigra", "Not you? Secure your account"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "New Sign-In Detected")}

    #{dgettext("sigra", "We noticed a new sign-in to your account from an unrecognized device or location.")}

    #{dgettext("sigra", "IP address:")} #{ip}
    #{dgettext("sigra", "Location:")} #{location}
    #{dgettext("sigra", "Device:")} #{device}
    #{dgettext("sigra", "Time:")} #{time}

    #{dgettext("sigra", "If this was you, you can safely ignore this email.")}

    #{dgettext("sigra", "Not you? Secure your account:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "New sign-in to your account"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email when a passkey is registered on an account."
  def passkey_registration_email(user, details) do
    ip = details |> Map.get(:ip, "Unknown") |> html_escape_string()
    city = details |> Map.get(:city, Map.get(details, :geo_city, "Unknown")) |> html_escape_string()
    device = details |> Map.get(:device, "Unknown device") |> html_escape_string()

    time =
      details
      |> Map.get(:time, DateTime.utc_now())
      |> format_security_time()
      |> html_escape_string()

    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "New Passkey Added")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "A new passkey was added to your account.")}
    </p>
    <div style="margin: 16px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px;">
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Device:")}</strong> #{device}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "IP address:")}</strong> #{ip}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Location:")}</strong> #{city}
      </p>
      <p style="margin: 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Time:")}</strong> #{time}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, you can safely ignore this email.")}
    </p>
    #{cta_button(dgettext("sigra", "Not you? Secure your account"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "New Passkey Added")}

    #{dgettext("sigra", "A new passkey was added to your account.")}

    #{dgettext("sigra", "Device:")} #{device}
    #{dgettext("sigra", "IP address:")} #{ip}
    #{dgettext("sigra", "Location:")} #{city}
    #{dgettext("sigra", "Time:")} #{time}

    #{dgettext("sigra", "If this was you, you can safely ignore this email.")}

    #{dgettext("sigra", "Not you? Secure your account:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "New passkey added to your account"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a lockout notification email."
  def lockout_notification_email(user, _details) do
    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Account Locked")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "We detected multiple failed login attempts on your account. For your security, your account has been temporarily locked for 15 minutes.")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, you can try again after the lockout period.")}
    </p>
    #{cta_button(dgettext("sigra", "Change your password"), reset_url)}
    <p style="margin: 12px 0 0 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If you did not attempt to log in, we recommend changing your password immediately.")}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Account Locked")}

    #{dgettext("sigra", "We detected multiple failed login attempts on your account. For your security, your account has been temporarily locked for 15 minutes.")}

    #{dgettext("sigra", "If this was you, you can try again after the lockout period.")}

    #{dgettext("sigra", "Change your password:")} #{reset_url}

    #{dgettext("sigra", "If you did not attempt to log in, we recommend changing your password immediately.")}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Your account has been temporarily locked"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email when MFA is enabled on an account."
  def mfa_enabled_email(user, _opts \\ []) do
    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Two-Factor Authentication Enabled")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Two-factor authentication has been enabled on your %{app_name} account. Your account is now more secure.", app_name: "ThreadlinePhoenix")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If you did not enable this, change your password immediately.")}
    </p>
    #{cta_button(dgettext("sigra", "Change your password"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "Two-Factor Authentication Enabled")}

    #{dgettext("sigra", "Two-factor authentication has been enabled on your %{app_name} account. Your account is now more secure.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "If you did not enable this, change your password immediately.")}

    #{dgettext("sigra", "Change your password:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Two-factor authentication enabled"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email when MFA is disabled on an account."
  def mfa_disabled_email(user, _opts \\ []) do
    settings_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/settings"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Two-Factor Authentication Disabled")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Two-factor authentication was disabled on your %{app_name} account. If this wasn't you, re-enable MFA and change your password.", app_name: "ThreadlinePhoenix")}
    </p>
    #{cta_button(dgettext("sigra", "Secure your account"), settings_url)}
    """

    text_body = """
    #{dgettext("sigra", "Two-Factor Authentication Disabled")}

    #{dgettext("sigra", "Two-factor authentication was disabled on your %{app_name} account. If this wasn't you, re-enable MFA and change your password.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "Secure your account:")} #{settings_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Two-factor authentication disabled"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email when a backup code is used to sign in."
  def backup_code_used_email(user, opts \\ []) do
    remaining = Keyword.get(opts, :remaining, 0)
    settings_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/settings"

    low_codes_warning =
      if remaining <= 2 do
        """
        <p style="margin: 0 0 12px 0; font-size: 16px; color: #dc2626; font-weight: 600; line-height: 1.5; font-family: #{@font_family};">
          #{dgettext("sigra", "You're running low on backup codes. Generate new ones to ensure you can always access your account.")}
        </p>
        """
      else
        ""
      end

    low_codes_text =
      if remaining <= 2 do
        "\n#{dgettext("sigra", "You're running low on backup codes. Generate new ones to ensure you can always access your account.")}\n"
      else
        ""
      end

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Backup Code Used")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "A backup code was used to sign in to your %{app_name} account. You have %{remaining} of 8 backup codes remaining.", app_name: "ThreadlinePhoenix", remaining: remaining)}
    </p>
    #{low_codes_warning}#{cta_button(dgettext("sigra", "Generate new backup codes"), settings_url)}
    """

    text_body = """
    #{dgettext("sigra", "Backup Code Used")}

    #{dgettext("sigra", "A backup code was used to sign in to your %{app_name} account. You have %{remaining} of 8 backup codes remaining.", app_name: "ThreadlinePhoenix", remaining: remaining)}
    #{low_codes_text}
    #{dgettext("sigra", "Generate new backup codes:")} #{settings_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Backup code used to sign in"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email when MFA verification is temporarily locked."
  def mfa_lockout_email(user, _opts \\ []) do
    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Verification Temporarily Locked")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "We detected multiple failed two-factor authentication attempts on your %{app_name} account. Verification has been temporarily locked for 15 minutes.", app_name: "ThreadlinePhoenix")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this was you, wait for the lockout to expire and try again. If this wasn't you, change your password immediately.")}
    </p>
    #{cta_button(dgettext("sigra", "Change your password"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "Verification Temporarily Locked")}

    #{dgettext("sigra", "We detected multiple failed two-factor authentication attempts on your %{app_name} account. Verification has been temporarily locked for 15 minutes.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "If this was you, wait for the lockout to expire and try again. If this wasn't you, change your password immediately.")}

    #{dgettext("sigra", "Change your password:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Too many failed verification attempts"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  ## Email Change Templates (D-09)

  @doc "Builds a confirmation email sent to the NEW email address during email change."
  def email_change_confirmation_email(_user, new_email, url) do
    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Confirm Email Change")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "You requested to change your %{app_name} account email to this address. Click the button below to confirm the change.", app_name: "ThreadlinePhoenix")}
    </p>
    #{cta_button(dgettext("sigra", "Confirm new email address"), url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or confirm via this link:")} #{url}
    </p>
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "This link expires in 24 hours.")}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Confirm Email Change")}

    #{dgettext("sigra", "You requested to change your %{app_name} account email to this address. Click the button below to confirm the change.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "Confirm via this link:")} #{url}

    #{dgettext("sigra", "This link expires in 24 hours.")}

    ---
    #{footer_text()}
    """

    base_email(new_email)
    |> subject(dgettext("sigra", "Confirm your new email address"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a notification email sent to the OLD email address during email change."
  def email_change_notification_email(user, new_email, cancel_url) do
    escaped_new_email = html_escape_string(new_email)

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Email Change Requested")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Someone requested to change your %{app_name} account email from this address to %{new_email}. If this was you, no action is needed -- confirm the change from your new email.", app_name: "ThreadlinePhoenix", new_email: escaped_new_email)}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #dc2626; font-weight: 600; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If you did not request this change, click below to cancel it immediately.")}
    </p>
    #{cta_button(dgettext("sigra", "Cancel email change"), cancel_url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or cancel via this link:")} #{cancel_url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Email Change Requested")}

    #{dgettext("sigra", "Someone requested to change your %{app_name} account email from this address to %{new_email}. If this was you, no action is needed -- confirm the change from your new email.", app_name: "ThreadlinePhoenix", new_email: new_email)}

    #{dgettext("sigra", "If you did not request this change, click below to cancel it immediately.")}

    #{dgettext("sigra", "Cancel via this link:")} #{cancel_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Email change requested for your account"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a post-change confirmation email sent to the NEW email address after email change completes."
  def email_changed_email(user) do
    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Email Updated")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Your %{app_name} account email has been changed to this address. If you did not make this change, secure your account immediately.", app_name: "ThreadlinePhoenix")}
    </p>
    #{cta_button(dgettext("sigra", "Secure your account"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "Email Updated")}

    #{dgettext("sigra", "Your %{app_name} account email has been changed to this address. If you did not make this change, secure your account immediately.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "Secure your account:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Your email has been updated"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  ## Account Deletion Templates (D-21)

  @doc "Builds a deletion scheduled notification email."
  def deletion_scheduled_email(user, scheduled_date, cancel_url) do
    formatted_date = format_date(scheduled_date)

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Account Deletion Scheduled")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Your %{app_name} account has been deactivated and is scheduled for permanent deletion on %{date}. All sessions have been signed out.", app_name: "ThreadlinePhoenix", date: formatted_date)}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Changed your mind? You can cancel the deletion before the scheduled date.")}
    </p>
    #{cta_button(dgettext("sigra", "Cancel account deletion"), cancel_url)}
    <p style="margin: 12px 0 0 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family}; word-break: break-all;">
      #{dgettext("sigra", "Or cancel via this link:")} #{cancel_url}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Account Deletion Scheduled")}

    #{dgettext("sigra", "Your %{app_name} account has been deactivated and is scheduled for permanent deletion on %{date}. All sessions have been signed out.", app_name: "ThreadlinePhoenix", date: formatted_date)}

    #{dgettext("sigra", "Changed your mind? You can cancel the deletion before the scheduled date.")}

    #{dgettext("sigra", "Cancel via this link:")} #{cancel_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Your account is scheduled for deletion"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a deletion cancelled confirmation email."
  def deletion_cancelled_email(user, login_url) do
    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Deletion Cancelled")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Your %{app_name} account deletion has been cancelled. Your account is active again. You can log in as usual.", app_name: "ThreadlinePhoenix")}
    </p>
    #{cta_button(dgettext("sigra", "Log in to your account"), login_url)}
    """

    text_body = """
    #{dgettext("sigra", "Deletion Cancelled")}

    #{dgettext("sigra", "Your %{app_name} account deletion has been cancelled. Your account is active again. You can log in as usual.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "Log in to your account:")} #{login_url}

    ---
    #{footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Account deletion cancelled"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  @doc "Builds a deletion finalized notification email. Accepts raw email since user may be anonymized."
  def deletion_finalized_email(email) do
    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Account Deleted")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Your %{app_name} account and associated data have been permanently removed. If you'd like to use %{app_name} again in the future, you're welcome to create a new account.", app_name: "ThreadlinePhoenix")}
    </p>
    """

    text_body = """
    #{dgettext("sigra", "Account Deleted")}

    #{dgettext("sigra", "Your %{app_name} account and associated data have been permanently removed. If you'd like to use %{app_name} again in the future, you're welcome to create a new account.", app_name: "ThreadlinePhoenix")}

    ---
    #{footer_text()}
    """

    base_email(email)
    |> subject(dgettext("sigra", "Your account has been deleted"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  ## Password Change Template (D-37)

  @doc "Builds a password changed notification email with login details."
  def password_changed_email(user, details) do
    ip = details |> Map.get(:ip, "Unknown") |> html_escape_string()
    geo_city = Map.get(details, :geo_city)
    geo_country = Map.get(details, :geo_country_code)

    location =
      if geo_city do
        "#{html_escape_string(geo_city)}, #{html_escape_string(geo_country)}"
      else
        "Unknown"
      end

    device = details |> Map.get(:device, "Unknown device") |> html_escape_string()

    time =
      Map.get(details, :time, DateTime.utc_now())
      |> Calendar.strftime("%Y-%m-%d %H:%M:%S UTC")

    reset_url = "#{ThreadlinePhoenixWeb.Endpoint.url()}/users/reset-password"

    html_content = """
    <p style="margin: 0 0 16px 0; font-size: 20px; font-weight: 600; color: #18181b; line-height: 1.2; font-family: #{@font_family};">
      #{dgettext("sigra", "Password Changed")}
    </p>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "Your %{app_name} account password was changed.", app_name: "ThreadlinePhoenix")}
    </p>
    <div style="margin: 16px 0; padding: 16px; background-color: #f4f4f5; border-radius: 8px;">
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "IP address:")}</strong> #{ip}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Location:")}</strong> #{location}
      </p>
      <p style="margin: 0 0 8px 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Device:")}</strong> #{device}
      </p>
      <p style="margin: 0; font-size: 14px; color: #3f3f46; line-height: 1.5; font-family: #{@font_family};">
        <strong>#{dgettext("sigra", "Time:")}</strong> #{time}
      </p>
    </div>
    <p style="margin: 0 0 12px 0; font-size: 16px; color: #dc2626; font-weight: 600; line-height: 1.5; font-family: #{@font_family};">
      #{dgettext("sigra", "If this wasn't you, reset your password immediately.")}
    </p>
    #{cta_button(dgettext("sigra", "Reset your password"), reset_url)}
    """

    text_body = """
    #{dgettext("sigra", "Password Changed")}

    #{dgettext("sigra", "Your %{app_name} account password was changed.", app_name: "ThreadlinePhoenix")}

    #{dgettext("sigra", "IP address:")} #{ip}
    #{dgettext("sigra", "Location:")} #{location}
    #{dgettext("sigra", "Device:")} #{device}
    #{dgettext("sigra", "Time:")} #{time}

    #{dgettext("sigra", "If this wasn't you, reset your password immediately.")}

    #{dgettext("sigra", "Reset your password:")} #{reset_url}

    ---
    #{security_footer_text()}
    """

    base_email(user.email)
    |> subject(dgettext("sigra", "Your password was changed"))
    |> html_body(base_layout(html_content))
    |> text_body(text_body)
  end

  # -- Org-invite block (Phase 17 D-12 / Phase 24 D-04) --
  #
  # Canonical inline copy of the invitation email fragment shipped at
  # priv/templates/sigra.install/organizations/organization_invitation_email.ex.
  # Both must stay in sync — the fragment file is the documentation reference.
  # Wrapped in `<%= if organizations? do %%>` so --no-organizations omits it.


  # -- Private helpers --

  defp base_email(to) do
    new()
    |> to(to)
    |> from(@from_address)
  end

  defp base_layout(content_html) do
    """
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <title>ThreadlinePhoenix</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: #{@font_family};">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color: #f4f4f5;">
        <tr>
          <td align="center" style="padding: 24px 16px;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width: 600px; width: 100%;">
              <!-- Header -->
              <tr>
                <td align="center" style="padding: 24px 16px 12px 16px;">
                  <h1 style="margin: 0; font-size: 24px; font-weight: 700; line-height: 1.2; color: #18181b; font-family: #{@font_family};">
                    ThreadlinePhoenix
                  </h1>
                </td>
              </tr>
              <!-- Content Card -->
              <tr>
                <td>
                  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color: #ffffff; border: 1px solid #e4e4e7; border-radius: 8px;">
                    <tr>
                      <td style="padding: 24px 16px;">
                        #{content_html}
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
              <!-- Footer -->
              <tr>
                <td align="center" style="padding: 24px 16px;">
                  <p style="margin: 0; font-size: 14px; color: #71717a; line-height: 1.5; font-family: #{@font_family};">
                    #{footer_text()}
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
    """
  end

  defp cta_button(label, url) do
    """
    <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="margin: 24px 0;">
      <tr>
        <td align="center">
          <a href="#{url}" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: #ffffff; font-size: 16px; font-weight: 700; line-height: 1.0; font-family: #{@font_family}; text-decoration: none; border-radius: 8px;" role="link">
            #{label}
          </a>
        </td>
      </tr>
    </table>
    """
  end

  defp footer_text do
    dgettext(
      "sigra",
      "You're receiving this email because you have an account with %{app_name}. If you didn't request this, you can safely ignore this email.",
      app_name: "ThreadlinePhoenix"
    )
  end

  defp security_footer_text do
    dgettext(
      "sigra",
      "You received this email because your %{app_name} account experienced a security event.",
      app_name: "ThreadlinePhoenix"
    )
  end

  defp html_escape_string(value) when is_binary(value) do
    Phoenix.HTML.html_escape(value) |> Phoenix.HTML.safe_to_string()
  end

  defp html_escape_string(value), do: html_escape_string(to_string(value))

  defp format_security_time(%DateTime{} = datetime) do
    Calendar.strftime(datetime, "%Y-%m-%d %H:%M:%S UTC")
  end

  defp format_security_time(value) when is_binary(value), do: value
  defp format_security_time(value), do: to_string(value)

  defp format_date(%DateTime{} = datetime) do
    Calendar.strftime(datetime, "%B %d, %Y")
  end

  defp format_date(%Date{} = date) do
    Calendar.strftime(date, "%B %d, %Y")
  end
end
