defmodule ThreadlinePhoenix.Accounts.Mailer do
  @moduledoc """
  Mailer implementation for Sigra authentication emails.

  Implements the `Sigra.Mailer` behaviour by building a `Swoosh.Email`
  struct and delivering via the host app's Swoosh mailer.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """
  @behaviour Sigra.Mailer

  @impl Sigra.Mailer
  def deliver(to, subject, body) do
    email = build_email(to, subject, body)

    case ThreadlinePhoenix.Mailer.deliver(email) do
      {:ok, _metadata} = ok -> ok
      {:error, _reason} = error -> error
    end
  end

  defp build_email(to, subject, body) when is_binary(body) do
    import Swoosh.Email

    new()
    |> to(to)
    |> from({"ThreadlinePhoenix", "noreply@example.com"})
    |> subject(subject)
    |> text_body(body)
  end

  defp build_email(to, subject, %{html: html, text: text}) do
    import Swoosh.Email

    new()
    |> to(to)
    |> from({"ThreadlinePhoenix", "noreply@example.com"})
    |> subject(subject)
    |> html_body(html)
    |> text_body(text)
  end

  defp build_email(to, subject, %{text: text}) do
    build_email(to, subject, text)
  end
end
