defmodule ThreadlinePhoenix.Accounts.UserBackupCode do
  @moduledoc """
  Ecto schema for MFA backup/recovery codes.

  Each row represents a single backup code. Codes are SHA-256 hashed
  before storage. Consumption is atomic via `used_at` timestamp.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "user_backup_codes" do
    belongs_to :user, ThreadlinePhoenix.Accounts.User
    field :hashed_code, :string
    field :used_at, :utc_datetime_usec

    timestamps(type: :utc_datetime_usec, updated_at: false)
  end

  @doc "Changeset for inserting a hashed backup code."
  def changeset(backup_code \\ %__MODULE__{}, attrs) do
    backup_code
    |> cast(attrs, [:user_id, :hashed_code])
    |> validate_required([:user_id, :hashed_code])
    |> foreign_key_constraint(:user_id)
  end
end
