defmodule ThreadlinePhoenix.Accounts.UserSession do
  @moduledoc """
  Ecto schema for database-backed user sessions.

  Each session tracks the authenticated user, connection metadata (IP,
  user agent, geolocation), and temporal data (last activity, sudo mode).

  Maps to/from the `Sigra.Session` library struct. The library handles
  all security-critical session operations; this schema provides the
  Ecto persistence layer in your application.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """

  use Ecto.Schema

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  schema "user_sessions" do
    field :hashed_token, :binary
    field :type, :string, default: "standard"
    field :ip, :string
    field :user_agent, :string
    field :geo_city, :string
    field :geo_country_code, :string
    field :last_active_at, :utc_datetime_usec
    field :sudo_at, :utc_datetime_usec
    field :active_organization_id, :binary_id

    belongs_to :user, ThreadlinePhoenix.Accounts.User

    timestamps(type: :utc_datetime_usec, updated_at: false)
  end
end
