defmodule ThreadlinePhoenix.Vault do
  @moduledoc """
  Cloak vault for encrypting Sigra-managed secrets at rest.

  Uses AES-256-GCM encryption with a key derived from the `CLOAK_KEY`
  environment variable. The key must be a 32-byte value encoded as Base64.

  ## Generating a key

      32 |> :crypto.strong_rand_bytes() |> Base.encode64()

  Store the result in your environment as `CLOAK_KEY`.

  Generated by `mix sigra.install`. Customize freely; this module is owned by
  your application.
  """

  use Cloak.Vault, otp_app: :threadline_phoenix

  @impl GenServer
  def init(config) do
    config =
      Keyword.put(config, :ciphers,
        default: {
          Cloak.Ciphers.AES.GCM,
          tag: "AES.GCM.V1",
          key: decode_env!("CLOAK_KEY"),
          iv_length: 12
        }
      )

    {:ok, config}
  end

  defp decode_env!(var) do
    var
    |> System.fetch_env!()
    |> Base.decode64!()
  end
end
