defmodule ThreadlinePhoenixWeb.ConfirmationHTML do
  @moduledoc """
  Controller-mode confirmation templates for non-LiveView installs.

  Provides code entry, already-confirmed, and expired token pages.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use ThreadlinePhoenixWeb, :html

  use Gettext, backend: ThreadlinePhoenixWeb.Gettext

  def new(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Confirm your email")}
        <:subtitle>
          {dgettext("sigra", "Enter the 6-digit code we sent to your email, or check your inbox for a confirmation link.")}
        </:subtitle>
      </.header>

      <.form for={%{}} id="confirmation_form" action={~p"/users/confirm"} method="post">
        <.input
          name="code"
          type="text"
          label={dgettext("sigra", "Confirmation code")}
          inputmode="numeric"
          autocomplete="one-time-code"
          maxlength="6"
          pattern="[0-9]{6}"
          aria-label={dgettext("sigra", "Confirmation code")}
          required
        />

        <.button class="btn btn-primary w-full">
          {dgettext("sigra", "Confirm email")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>

      <p class="mt-4 text-center text-sm">
        <.link href={~p"/users/confirm/resend"} method="post" class="font-semibold text-brand hover:underline">
          {dgettext("sigra", "Didn't receive a code?")}
        </.link>
      </p>
    </div>
    """
  end

  def already_confirmed(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Email already confirmed")}
        <:subtitle>
          {dgettext("sigra", "Your email was already confirmed. You can log in below.")}
        </:subtitle>
      </.header>

      <p class="mt-4 text-center">
        <.link navigate={~p"/users/log_in"} class="font-semibold text-brand hover:underline">
          {dgettext("sigra", "Log in")}
        </.link>
      </p>
    </div>
    """
  end

  def expired(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Confirmation link expired")}
        <:subtitle>
          {dgettext("sigra", "This confirmation link has expired or was already used.")}
        </:subtitle>
      </.header>

      <.form for={%{}} action={~p"/users/confirm/resend"} method="post">
        <.button class="btn btn-primary w-full">
          {dgettext("sigra", "Send new confirmation email")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>
    </div>
    """
  end
end
