defmodule ThreadlinePhoenixWeb.ConfirmationController do
  @moduledoc """
  Controller for email confirmation flow.

  Handles link-based confirmation (GET), code-based confirmation (POST),
  and resend requests. Expired and already-confirmed states render
  dedicated pages with actionable next steps.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """
  use ThreadlinePhoenixWeb, :controller

  use Gettext, backend: ThreadlinePhoenixWeb.Gettext

  alias ThreadlinePhoenix.Accounts, as: Auth

  def new(conn, _params) do
    render(conn, :new)
  end

  def create(conn, %{"code" => code}) do
    user = conn.assigns.current_scope.user

    case Auth.confirm_user_by_code(user, code) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
        |> redirect(to: ~p"/")

      {:error, :invalid_code} ->
        conn
        |> put_flash(:error, dgettext("sigra", "Invalid confirmation code. Please try again."))
        |> render(:new)

      {:error, :rate_limited} ->
        conn
        |> put_flash(
          :error,
          dgettext("sigra", "Too many attempts. Please wait a few minutes before trying again.")
        )
        |> render(:new)

      {:error, :already_confirmed} ->
        conn
        |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
        |> redirect(to: ~p"/")
    end
  end

  def confirm(conn, %{"token" => token}) do
    case Auth.confirm_user(token) do
      {:ok, _user} ->
        conn
        |> put_flash(:info, dgettext("sigra", "Your email has been confirmed."))
        |> redirect(to: ~p"/")

      {:error, :already_confirmed} ->
        render(conn, :already_confirmed)

      {:error, :token_expired} ->
        render(conn, :expired)

      {:error, :token_invalid} ->
        conn
        |> put_flash(
          :error,
          dgettext("sigra", "This confirmation link is invalid or has expired.")
        )
        |> redirect(to: ~p"/users/confirm")
    end
  end

  def resend(conn, _params) do
    user = conn.assigns.current_scope.user

    case Auth.deliver_user_confirmation_instructions(user, &url(conn, ~p"/users/confirm/#{&1}")) do
      {:ok, _} ->
        conn
        |> put_flash(:info, dgettext("sigra", "A new confirmation email has been sent."))
        |> redirect(to: ~p"/users/confirm")

      {:error, :already_confirmed} ->
        conn
        |> put_flash(:info, dgettext("sigra", "Your email is already confirmed."))
        |> redirect(to: ~p"/")
    end
  end
end
