defmodule ThreadlinePhoenixWeb.MFAChallengeHTML do
  @moduledoc """
  Controller-mode MFA challenge templates for non-LiveView installs.

  Provides the two-factor authentication verification page with
  TOTP authenticator code and backup code tabs.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use ThreadlinePhoenixWeb, :html

  def mfa_challenge(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        Two-factor authentication
        <:subtitle>
          Enter the code for {@masked_email}
        </:subtitle>
      </.header>

      <% # Tab bar (D-21) %>
      <div class="mt-6" role="tablist" aria-label="Verification method">
        <div class="flex border-b border-gray-200">
          <button
            type="button"
            role="tab"
            id="tab-totp"
            aria-selected={@tab == "totp"}
            aria-controls="panel-totp"
            class={"px-4 py-2 text-sm font-semibold border-b-2 -mb-px #{if @tab == "totp", do: "border-brand text-brand", else: "border-transparent text-gray-500 hover:text-gray-700"}"}
            onclick="switchTab('totp')"
          >
            Authenticator code
          </button>
          <button
            type="button"
            role="tab"
            id="tab-backup"
            aria-selected={@tab == "backup"}
            aria-controls="panel-backup"
            class={"px-4 py-2 text-sm font-semibold border-b-2 -mb-px #{if @tab == "backup", do: "border-brand text-brand", else: "border-transparent text-gray-500 hover:text-gray-700"}"}
            onclick="switchTab('backup')"
          >
            Backup code
          </button>
        </div>
      </div>

      <% # TOTP Tab Content %>
      <div
        id="panel-totp"
        role="tabpanel"
        aria-labelledby="tab-totp"
        class={"mt-6 #{if @tab != "totp", do: "hidden"}"}
      >
        <.form for={%{}} id="mfa_totp_form" action={~p"/users/mfa"} method="post">
          <input type="hidden" name="mfa[method]" value="totp" />

          <div class="space-y-4">
            <div>
              <label for="mfa_totp_code" class="block text-sm font-semibold leading-normal text-zinc-800">
                Authenticator code
              </label>
              <input
                type="text"
                id="mfa_totp_code"
                name="mfa[code]"
                inputmode="numeric"
                pattern="[0-9]*"
                maxlength="6"
                autocomplete="one-time-code"
                autofocus
                required
                class="mt-2 block w-full rounded-lg text-base font-mono text-center tracking-widest text-zinc-900 focus:ring-0 sm:text-sm/6 phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 border-zinc-300 focus:border-zinc-400"
                aria-label="6-digit authenticator code"
              />
            </div>

            <label class="flex items-center gap-2 text-sm text-gray-600">
              <input type="checkbox" name="mfa[trust]" value="true" class="rounded border-gray-300" />
              Trust this browser for 30 days
            </label>

            <.button class="w-full">
              Verify
            </.button>
          </div>
        </.form>
      </div>

      <% # Backup Code Tab Content %>
      <div
        id="panel-backup"
        role="tabpanel"
        aria-labelledby="tab-backup"
        class={"mt-6 #{if @tab != "backup", do: "hidden"}"}
      >
        <.form for={%{}} id="mfa_backup_form" action={~p"/users/mfa"} method="post">
          <input type="hidden" name="mfa[method]" value="backup" />

          <div class="space-y-4">
            <div>
              <label for="mfa_backup_code" class="block text-sm font-semibold leading-normal text-zinc-800">
                Backup code
              </label>
              <input
                type="text"
                id="mfa_backup_code"
                name="mfa[code]"
                placeholder="XXXX-XXXX"
                required
                class="mt-2 block w-full rounded-lg text-base font-mono text-zinc-900 focus:ring-0 sm:text-sm/6 phx-no-feedback:border-zinc-300 phx-no-feedback:focus:border-zinc-400 border-zinc-300 focus:border-zinc-400"
                aria-label="Backup code"
              />
            </div>

            <.button class="w-full">
              Verify
            </.button>
          </div>
        </.form>
      </div>

      <% # Remaining attempts hint (D-38) %>
      <div class="mt-4 text-center" aria-live="polite">
        <p class="text-sm text-gray-500">
          Enter the code from your authenticator app to continue.
        </p>
      </div>

      <% # Cancel link (D-34) %>
      <p class="mt-6 text-center text-sm">
        <.link href={~p"/users/log_out"} method="delete" class="text-gray-500 hover:underline">
          Cancel and sign out
        </.link>
      </p>
    </div>

    <% # Tab switching JS %>
    <script>
      function switchTab(tab) {
        // Update tab buttons
        document.querySelectorAll('[role="tab"]').forEach(function(btn) {
          var isActive = btn.id === 'tab-' + tab;
          btn.setAttribute('aria-selected', isActive);
          if (isActive) {
            btn.className = btn.className.replace('border-transparent text-gray-500 hover:text-gray-700', 'border-brand text-brand');
          } else {
            btn.className = btn.className.replace('border-brand text-brand', 'border-transparent text-gray-500 hover:text-gray-700');
          }
        });
        // Update tab panels
        document.querySelectorAll('[role="tabpanel"]').forEach(function(panel) {
          if (panel.id === 'panel-' + tab) {
            panel.classList.remove('hidden');
            var input = panel.querySelector('input[name="mfa[code]"]');
            if (input) input.focus();
          } else {
            panel.classList.add('hidden');
          }
        });
      }

      // Auto-submit TOTP when 6 digits entered (D-36)
      document.addEventListener('DOMContentLoaded', function() {
        var totpInput = document.getElementById('mfa_totp_code');
        if (totpInput) {
          totpInput.addEventListener('input', function() {
            if (this.value.length === 6 && /^\d{6}$/.test(this.value)) {
              this.closest('form').requestSubmit();
            }
          });
        }
      });
    </script>
    """
  end
end
