defmodule ThreadlinePhoenixWeb.MFAChallengeController do
  @moduledoc """
  Controller for the MFA challenge page.

  Handles the two-factor authentication verification step after
  password or OAuth login for users with MFA enabled. Supports
  both TOTP authenticator codes and backup codes.

  Generated by `mix sigra.install`. Customize freely -- this module
  is owned by your application.
  """
  use ThreadlinePhoenixWeb, :controller

  alias ThreadlinePhoenix.Accounts, as: Auth

  def new(conn, _params) do
    scope = conn.assigns[:current_scope]

    cond do
      is_nil(scope) ->
        conn |> redirect(to: ~p"/users/log_in") |> halt()

      !match?(%{type: :mfa_pending}, conn.private[:sigra_session]) ->
        # Not in MFA pending state -- redirect appropriately (D-35)
        conn |> redirect(to: ~p"/") |> halt()

      true ->
        user = scope.user
        masked_email = mask_email(user.email)
        render(conn, :mfa_challenge, masked_email: masked_email, tab: "totp")
    end
  end

  def create(conn, %{"mfa" => mfa_params}) do
    user = conn.assigns.current_scope.user
    code = mfa_params["code"] || ""
    trust = mfa_params["trust"] == "true"
    method = if mfa_params["method"] == "backup", do: :backup, else: :totp

    result =
      case method do
        :totp -> Auth.mfa_verify(user, code)
        :backup -> Auth.mfa_verify_backup(user, code)
      end

    case result do
      {:ok, _} ->
        return_to = get_session(conn, :mfa_return_to) || ~p"/"

        conn
        |> delete_session(:mfa_pending)
        |> delete_session(:mfa_return_to)
        |> delete_session(:mfa_remember_me)
        |> maybe_set_trust_cookie(user, trust)
        |> put_flash(:info, "Two-factor authentication verified.")
        |> redirect(to: return_to)

      {:error, :invalid_code, remaining} ->
        masked_email = mask_email(user.email)

        conn
        |> put_flash(:error, "Invalid verification code. #{remaining} attempts remaining.")
        |> render(:mfa_challenge, masked_email: masked_email, tab: mfa_params["method"] || "totp")

      {:error, :invalid_backup_code, remaining} ->
        masked_email = mask_email(user.email)

        conn
        |> put_flash(:error, "Invalid verification code. #{remaining} attempts remaining.")
        |> render(:mfa_challenge, masked_email: masked_email, tab: "backup")

      {:error, :lockout, seconds} ->
        minutes = div(seconds + 59, 60)

        conn
        |> put_flash(:error, "Too many failed attempts. Try again in #{minutes} minutes.")
        |> render(:mfa_challenge, masked_email: mask_email(user.email), tab: "totp")

      {:error, :not_enrolled} ->
        conn
        |> put_flash(:error, "MFA is not enabled on your account.")
        |> redirect(to: ~p"/users/settings")
        |> halt()
    end
  end

  defp mask_email(email) do
    case String.split(email, "@") do
      [local, domain] ->
        first = String.first(local)
        "#{first}***@#{domain}"

      _ ->
        "***"
    end
  end

  defp maybe_set_trust_cookie(conn, user, true) do
    config = Auth.sigra_config()
    trust_ttl = Keyword.get(config.mfa, :trust_ttl, 2_592_000)
    trust_enabled = Keyword.get(config.mfa, :trust_enabled, true)

    if trust_enabled do
      trust_epoch = Map.get(user, :mfa_trust_epoch, 0)
      secret_key_base = conn.secret_key_base

      cookie = Sigra.MFA.Trust.sign(secret_key_base, user.id, trust_epoch, trust_ttl)

      Plug.Conn.put_resp_cookie(
        conn,
        Sigra.MFA.Trust.cookie_name(),
        cookie,
        Sigra.MFA.Trust.cookie_opts(config) ++ [max_age: trust_ttl]
      )
    else
      conn
    end
  end

  defp maybe_set_trust_cookie(conn, _user, _), do: conn
end
