defmodule ThreadlinePhoenixWeb.MFASettingsHTML do
  @moduledoc """
  Controller-mode MFA settings and enrollment templates.

  Provides the MFA enrollment, backup code display, settings card,
  and disable confirmation for non-LiveView installs.

  Generated by `mix sigra.install --no-live`. Customize freely -- this module
  is owned by your application.
  """
  use ThreadlinePhoenixWeb, :html

  @doc """
  Renders the MFA settings section.

  Assigns expected:
  - `@mfa_enabled` - boolean
  - `@backup_remaining` - integer
  - `@enrollment_step` - nil | :qr | :backup_codes
  - `@svg` - QR code SVG string (when enrolling)
  - `@base32_secret` - base32 TOTP secret (when enrolling)
  - `@backup_codes` - list of backup code strings
  - `@show_disable` - boolean
  """
  def mfa_settings(assigns) do
    ~H"""
    <div class="mx-auto max-w-2xl">
      <%= if @mfa_enabled do %>
        <% # Surface 3: MFA Settings Card %>
        <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
          <div class="flex justify-between items-center">
            <div>
              <span class="text-sm font-semibold">Two-factor authentication</span>
              <span class="ml-2 inline-flex items-center text-green-700 bg-green-50 text-xs px-2 py-0.5 rounded-full font-semibold">
                Enabled
              </span>
            </div>
            <.link
              href={~p"/users/settings/mfa/disable"}
              class="text-sm text-red-600 bg-red-50 hover:bg-red-100 px-3 py-1.5 rounded-md"
            >
              Disable
            </.link>
          </div>

          <% # Backup code status (D-15) %>
          <div class="mt-3">
            <%= cond do %>
              <% @backup_remaining == 0 -> %>
                <div class="text-red-600 bg-red-50 p-2 rounded text-sm">
                  All backup codes used. Generate new ones now.
                </div>
              <% @backup_remaining <= 2 -> %>
                <div class="text-yellow-700 bg-yellow-50 p-2 rounded text-sm">
                  {@backup_remaining} of 8 backup codes remaining
                </div>
              <% true -> %>
                <p class="text-sm text-gray-500">
                  {@backup_remaining} of 8 backup codes remaining
                </p>
            <% end %>

            <p class="mt-1">
              <.link
                href={~p"/users/settings/mfa/regenerate"}
                class="text-sm text-brand hover:underline"
              >
                Regenerate codes
              </.link>
            </p>
          </div>

          <% # Trust section %>
          <div class="mt-3">
            <.link
              href={~p"/users/settings/mfa/revoke-trust"}
              method="post"
              data-confirm="This will require two-factor authentication on all your browsers. Continue?"
              class="text-sm text-gray-500 hover:underline"
            >
              Revoke all trusted browsers
            </.link>
          </div>
        </div>

        <% # Surface 4: Disable Confirmation %>
        <%= if @show_disable do %>
          <div class="mt-4 bg-red-50 p-4 rounded-lg border border-red-200">
            <h3 class="text-sm font-semibold text-red-800">Disable two-factor authentication</h3>
            <p class="mt-1 text-sm text-red-700">
              This will remove the extra security on your account.
              You'll need to set it up again to re-enable.
            </p>

            <.form for={%{}} action={~p"/users/settings/mfa/disable"} method="post" class="mt-3">
              <div class="space-y-3">
                <div>
                  <label for="disable_code" class="block text-sm font-semibold text-red-800">
                    Enter your current 6-digit code or a backup code to confirm:
                  </label>
                  <input
                    type="text"
                    id="disable_code"
                    name="code"
                    inputmode="numeric"
                    class="mt-1 block w-full rounded-lg text-base font-mono text-zinc-900 border-red-300 focus:border-red-400 focus:ring-0"
                    required
                  />
                </div>

                <div class="flex items-center gap-3">
                  <button
                    type="submit"
                    class="text-sm text-red-600 bg-red-50 border border-red-300 hover:bg-red-100 px-3 py-1.5 rounded-md"
                  >
                    Disable two-factor authentication
                  </button>
                  <.link href={~p"/users/settings"} class="text-sm text-gray-500 hover:underline">
                    Cancel
                  </.link>
                </div>
              </div>
            </.form>
          </div>
        <% end %>

      <% else %>
        <% # Enrollment UI %>
        <%= case @enrollment_step do %>
          <% nil -> %>
            <.header>
              Two-Factor Authentication
              <:subtitle>Add an extra layer of security to your account.</:subtitle>
            </.header>

            <div class="mt-6">
              <.link href={~p"/users/settings/mfa/enroll"} class="btn btn-primary">
                Set up two-factor authentication
              </.link>
            </div>

          <% :qr -> %>
            <.header>
              Two-Factor Authentication
              <:subtitle>Add an extra layer of security to your account.</:subtitle>
            </.header>

            <div class="mt-6 space-y-6">
              <div class="text-center">
                <p class="text-sm text-gray-600 mb-4">
                  Scan this QR code with your authenticator app
                </p>
                <div
                  class="inline-block"
                  role="img"
                  aria-label="QR code for TOTP setup"
                >
                  {raw(@svg)}
                </div>
              </div>

              <div>
                <p class="text-sm text-gray-600">
                  Can't scan? Enter this key manually:
                </p>
                <div
                  class="mt-2 bg-gray-50 p-3 rounded-lg border border-gray-200 text-center"
                  style="user-select: all"
                >
                  <code class="text-sm font-mono break-all select-all">
                    {@base32_secret}
                  </code>
                </div>
              </div>

              <div>
                <p class="text-sm font-semibold">
                  Enter the 6-digit code from your app to verify setup:
                </p>

                <.form for={%{}} action={~p"/users/settings/mfa/confirm"} method="post" class="mt-3">
                  <div class="space-y-4">
                    <input
                      type="text"
                      name="code"
                      inputmode="numeric"
                      pattern="[0-9]*"
                      maxlength="6"
                      autocomplete="one-time-code"
                      autofocus
                      required
                      class="block w-full rounded-lg text-base font-mono text-center tracking-widest text-zinc-900 focus:ring-0 border-zinc-300 focus:border-zinc-400"
                      aria-label="6-digit verification code"
                    />

                    <.button class="w-full">
                      Enable two-factor authentication
                    </.button>
                  </div>
                </.form>
              </div>
            </div>

          <% :backup_codes -> %>
            <.header>
              Save your backup codes
              <:subtitle>
                Store these codes in a safe place. Each code can only be used once.
              </:subtitle>
            </.header>

            <div class="mt-4 bg-gray-50 p-4 rounded-lg">
              <ol class="grid grid-cols-2 gap-3">
                <%= for code <- @backup_codes do %>
                  <li class="text-center">
                    <code class="text-base font-mono">{code}</code>
                  </li>
                <% end %>
              </ol>
            </div>

            <div class="mt-4 flex gap-2">
              <button
                type="button"
                id="copy-backup-codes"
                onclick="copyBackupCodes()"
                class="inline-flex items-center gap-1 text-sm text-gray-600 bg-white border border-gray-300 hover:bg-gray-50 px-3 py-1.5 rounded-md"
              >
                <span id="copy-btn-text">Copy all</span>
              </button>
              <button
                type="button"
                id="download-backup-codes"
                onclick="downloadBackupCodes()"
                class="inline-flex items-center gap-1 text-sm text-gray-600 bg-white border border-gray-300 hover:bg-gray-50 px-3 py-1.5 rounded-md"
              >
                Download .txt
              </button>
            </div>

            <.form for={%{}} action={~p"/users/settings/mfa/complete"} method="post" class="mt-4">
              <label class="flex items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  name="acknowledged"
                  value="true"
                  required
                  class="rounded border-gray-300"
                />
                I have saved these backup codes in a safe place
              </label>

              <.button class="w-full mt-4">
                Done
              </.button>
            </.form>

            <script>
              function copyBackupCodes() {
                var codes = document.querySelectorAll('#panel-backup-codes code');
                var text = Array.from(codes).map(function(el) { return el.textContent.trim(); }).join('\n');
                navigator.clipboard.writeText(text).then(function() {
                  var btn = document.getElementById('copy-btn-text');
                  btn.textContent = 'Copied!';
                  setTimeout(function() { btn.textContent = 'Copy all'; }, 2000);
                });
              }

              function downloadBackupCodes() {
                var codes = document.querySelectorAll('#panel-backup-codes code');
                var text = Array.from(codes).map(function(el) { return el.textContent.trim(); }).join('\n');
                var blob = new Blob([text], { type: 'text/plain' });
                var url = URL.createObjectURL(blob);
                var a = document.createElement('a');
                a.href = url;
                a.download = 'backup-codes.txt';
                a.click();
                URL.revokeObjectURL(url);
              }
            </script>
        <% end %>
      <% end %>
    </div>
    """
  end
end
