defmodule ThreadlinePhoenixWeb.RegistrationHTML do
  @moduledoc """
  Controller-mode registration templates for non-LiveView installs.

  Generated by `mix sigra.install --no-live`. Provides the same registration
  form as the LiveView version, but without real-time password strength
  feedback (that requires LiveView's phx-change).
  """
  use ThreadlinePhoenixWeb, :html

  def new(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        Register
        <:subtitle>
          Already registered?
          <.link navigate={~p"/users/log_in"} class="font-semibold text-brand hover:underline">
            Log in
          </.link>
          to your account now.
        </:subtitle>
      </.header>

      <.form :let={f} for={@form} id="registration_form" action={~p"/users/register"} method="post">
        <% # Add custom fields here (e.g., :name, :company) %>
        <.input field={f[:email]} type="email" label="Email" autocomplete="username" required />
        <.input field={f[:password]} type="password" label="Password" autocomplete="new-password" required />



        <.button class="btn btn-primary w-full">
          Create an account <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>
    </div>
    """
  end
end
