defmodule ThreadlinePhoenixWeb.ResetPasswordController do
  @moduledoc """
  Controller for password reset flows.

  Handles requesting a password reset email, displaying the
  new password form, and processing the password change.

  Generated by `mix sigra.install --no-live`.
  """
  use ThreadlinePhoenixWeb, :controller

  @doc """
  Renders the "request reset" form where the user enters their email.
  """
  def new(conn, _params) do
    render(conn, :new)
  end

  @doc """
  Processes the reset request. Always shows the same message
  regardless of whether the email exists (enumeration prevention, D-38).
  """
  def create(conn, %{"user" => %{"email" => email}}) do
    if user = ThreadlinePhoenix.Accounts.get_user_by_email(email) do
      ThreadlinePhoenix.Accounts.deliver_user_reset_password_instructions(
        user,
        &url(conn, ~p"/users/reset-password/#{&1}")
      )
    end

    conn
    |> put_flash(
      :info,
      dgettext(
        "sigra",
        "If your email is in our system, you will receive reset instructions shortly."
      )
    )
    |> redirect(to: ~p"/users/log_in")
  end

  @doc """
  Renders the new password form for a valid reset token.
  Shows the expired page if the token is invalid or expired.
  """
  def edit(conn, %{"token" => token}) do
    case ThreadlinePhoenix.Accounts.get_user_by_reset_password_token(token) do
      nil ->
        render(conn, :expired)

      user ->
        changeset = ThreadlinePhoenix.Accounts.change_user_password(user)
        render(conn, :edit, changeset: changeset, token: token, user: user)
    end
  end

  @doc """
  Processes the password change. On success, invalidates all sessions
  and auto-logs the user in (D-29).
  """
  def update(conn, %{"token" => token, "user" => password_params}) do
    case ThreadlinePhoenix.Accounts.get_user_by_reset_password_token(token) do
      nil ->
        render(conn, :expired)

      user ->
        # 10.1 IN-03: pass the signed `token` (not the user struct) so the
        # reset routes through `Sigra.Auth.reset_password/4` — which rewinds
        # the HMAC signature, emits `[:sigra, :reset, :completed]` telemetry,
        # and writes the `auth.password_reset_complete` audit row. Passing a
        # user struct would invoke the legacy clause which bypasses all three.
        case ThreadlinePhoenix.Accounts.reset_user_password(token, password_params) do
          {:ok, _user} ->
            conn
            |> put_flash(:info, dgettext("sigra", "Your password has been reset."))
            |> ThreadlinePhoenixWeb.UserAuth.log_in_user(user)

          {:error, changeset} ->
            render(conn, :edit, changeset: changeset, token: token, user: user)
        end
    end
  end
end
