defmodule ThreadlinePhoenixWeb.ResetPasswordHTML do
  @moduledoc """
  Controller-mode reset password templates for non-LiveView installs.

  Generated by `mix sigra.install --no-live`. Provides the request form,
  new password form, and expired token page for password reset flows.
  """
  use ThreadlinePhoenixWeb, :html

  @doc """
  Renders the "request reset" form where the user enters their email.
  """
  def new(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Forgot your password?")}
        <:subtitle>
          {dgettext("sigra", "Enter your email and we'll send you a reset link.")}
        </:subtitle>
      </.header>

      <.form for={%{}} as={:user} id="reset_password_request_form" action={~p"/users/reset-password"} method="post">
        <.input name="user[email]" type="email" label={dgettext("sigra", "Email")} autocomplete="username" required />

        <.button class="btn btn-primary w-full">
          {dgettext("sigra", "Send reset instructions")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>

      <p class="mt-4 text-center text-sm">
        <.link navigate={~p"/users/log_in"} class="font-semibold text-brand hover:underline">
          {dgettext("sigra", "Back to log in")}
        </.link>
      </p>
    </div>
    """
  end

  @doc """
  Renders the new password form with confirmation field.
  """
  def edit(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Reset your password")}
        <:subtitle>
          {dgettext("sigra", "Enter your new password below.")}
        </:subtitle>
      </.header>

      <.form :let={f} for={@changeset} id="reset_password_form" action={~p"/users/reset-password/#{@token}"} method="put">
        <.input field={f[:password]} type="password" label={dgettext("sigra", "New password")} autocomplete="new-password" required />
        <.input field={f[:password_confirmation]} type="password" label={dgettext("sigra", "Confirm new password")} autocomplete="new-password" required />

        <.button class="btn btn-primary w-full">
          {dgettext("sigra", "Reset password")} <span aria-hidden="true">&rarr;</span>
        </.button>
      </.form>
    </div>
    """
  end

  @doc """
  Renders the expired/used token error page with a re-request button.
  Never a dead end (D-07/D-30).
  """
  def expired(assigns) do
    ~H"""
    <div class="mx-auto max-w-sm">
      <.header>
        {dgettext("sigra", "Reset link expired")}
        <:subtitle>
          {dgettext("sigra", "This password reset link has expired or was already used.")}
        </:subtitle>
      </.header>

      <div class="mt-6">
        <.link navigate={~p"/users/reset-password"} class="btn btn-primary w-full text-center block">
          {dgettext("sigra", "Request new reset email")}
        </.link>
      </div>
    </div>
    """
  end
end
